# user info
user:
  name: 喵帕斯先生
  first_name: miaopasi
  last_name: Mr.
  email: 1054662124
  domain: 站点域名
  avatar: /img/avatar.jpg
  describe: 网站简介。
  ruleText: 暂不接受个人博客以外的友链申请，确保您的网站内容积极向上，文章至少30篇，原创70%以上，部署HTTPS。

# logo
favicon:
  logo: /img/favicon.svg    #顶部 logo
  icon16: /img/favicon.svg   #icon 16*16
  icon32: /img/favicon.svg   #icon 32*32
  appleTouchIcon:   #apple-touch-icon.png   iOS 添加到桌面是图标
  webmanifest: #/site.webmanifest   应用程序清单文件
  visibilitychange: true  #是否在离开窗口时切换标题显示
  hidden: /failure.ico # Displays an icon when not visible  离开窗口时显示图标
  showText: (/≧▽≦/)咦！又好了！
  hideText: (●—●)喔哟，崩溃啦！

# Theme resource files or plug-ins
assets:
  plugin:
    row:
      css: css/plugins/bootstrap.row.css
    swup:
      js: //cdn.jsdelivr.net/npm/swup@2.0.19/dist/swup.min.js
    locomotive_scroll:
      css: //cdn.jsdelivr.net/npm/locomotive-scroll@4.1.4/dist/locomotive-scroll.min.css
      js: //cdn.jsdelivr.net/npm/locomotive-scroll@4.1.4/dist/locomotive-scroll.min.js
    fancybox: 
      css: //cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.css
      js: //cdn.jsdelivr.net/npm/@fancyapps/ui@4.0/dist/fancybox.umd.js
    typing:
      js: js/plugins/typing.js
    search:
      js: [//cdn.jsdelivr.net/npm/hexo-generator-searchdb@1.4.0/dist/search.js, js/plugins/local_search.js]
    swiper: 
      css: //cdn.jsdelivr.net/npm/swiper@4.5.1/dist/css/swiper.min.css
      js: //cdn.jsdelivr.net/npm/swiper@4.5.1/dist/js/swiper.min.js
    katex:
      js: //cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.js
      css: //cdn.jsdelivr.net/npm/katex@latest/dist/katex.min.css
      auto_render: //cdn.jsdelivr.net/npm/katex@latest/dist/contrib/auto-render.min.js
      copy_tex:
        css: //cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.css
        js: //cdn.jsdelivr.net/npm/katex@latest/dist/contrib/copy-tex.min.js
    bComments: [
      //imgcache.qq.com/qcloud/cloudbase-js-sdk/1.7.1/cloudbase.full.js,
      //cdn.jsdelivr.net/npm/b-comments@0.0.13/dist/index.all.min.js
    ]
    twikoo: //cdn.jsdelivr.net/npm/twikoo@1.6.7/dist/twikoo.all.min.js
  icons: 
    type: font # font symbol
    css:  css/plugins/font-awesome.min.css
    js:

# cdn
cdn:
  css:  
  js:
    head:
    base: 
    async: 
    defer: 

# The icon used by the theme
icons:
  sun: far fa-sun
  moon: far fa-moon
  play: fas fa-play
  email: far fa-envelope
  next: fas fa-arrow-right
  calendar: far fa-calendar-alt
  clock: far fa-clock
  user: far fa-user
  back_top: fas fa-arrow-up
  close: fas fa-times
  search: fas fa-search
  reward: fas fa-hand-holding-usd

# Top navigation menu
top_bars:
  - title: menu.home
    url: /
  - title: menu.archives
    url: /archives/
  - title: menu.tags
    url: /tags/
  - title: menu.links
    url: /links/
  - title: menu.about
    url: /about/
    # children:   #二级菜单
      # - title: about me
        # url: /about/me.md
    # noswup: true  #不使用局部刷新    

# Banner settings
banner:
  default:
    type: img
    bgurl: /img/banner.png
    bannerText: Hi my new friend!
    position: top
    fit: cover
  index:
    type: video
    bgurl: http://cdn.moji.com/websrc/video/autumn20190924.mp4
    bannerTitle: 树深时见鹿，<br>溪午不闻钟。
    bannerText: Hi my new friend!
    videoUrl: # http://cdn.moji.com/websrc/video/autumn20190924.mp4
  archive:
    bannerTitle: 云间连下榻，<br>天上接行杯。
    bannerText: The article archive
  links:
    bannerTitle: 莫愁前路无知己，<br>天下谁人不识君。
    bannerText: A link to a friend's website
  comment:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: The magic tree hole
  about:
    bannerTitle: 醉后不知天在水，<br>满船清梦压星河。
    bannerText: About me

# Sidebar settings
sidebar:
  typedTextPrefix: I`m
  typedText: [ 'Web Developer' ]
  info: 
    - key: sidebar.residence
      val: niverse
    - key: sidebar.city
      val: JiNan
    - key: sidebar.age
      val: 28
  social:
    - name: Github
      icon: fab fa-github
      url: https://github.com
    - name: Twitter
      icon: fab fa-twitter
      url: https://twitter.com
    - name: Rss  
      icon: fas fa-rss
      url: atom.xml

# About page settings
about:
  title: 如果一切都是镜花水月，那就让这万物走向终结。如果一切皆是命中注定，那就让这世界消失殆尽。
  introduction: 大家好，我是 <strong>Async</strong>，很高兴您能在浩瀚如烟的互联网世界里发现这个博客，更感谢您能够饶有兴致地浏览这个页面。建立这个 Blog 是出于兴趣爱好，我将在此分会分享一些学习笔记，可能还会分享少许图片、视频以及其他有趣东西的链接。
  blog: 
    <ul class="trm-list">
      <li>程序：Hexo </li>
      <li>主题：Hexo-theme-async </li>
    </ul>
  privacy: 
    本网站不会追踪访客行为，且不要求访客提供任何敏感信息（比如真实姓名、身份证号码、手机号等），因而也不存在任何隐私泄漏问题。访客参与评论，必须遵守法律法规和基本道德规范，文明礼貌。严禁发布任何有关淫秽、反动、暴力、博彩、恐吓、低俗的内容或违法信息，在尊重言论自由的同时请保持和平与理性。请勿对他人采取不友好的评论或其它过激行为。

# Footer settings
footer:
  # Hexo link (Powered by Hexo).
  powered:
    enable: false
  # Beian icp information for Chinese users. In China, every legal website should have a beian icp in website footer.
  # https://beian.miit.gov.cn/
  beian:
    enable: false
    icp: 
  # Copyright date
  copyrightYear: 2022
  # 
  live_time:
    enable: true
    prefix: footer.tips
    start_time: 04/10/2022 17:00:00
  #
  custom_text:  <span class="tips"><div id="go-fav">更多精彩文章，按<span>Ctrl</span>+<span>D</span>收藏本站！</div></span>

# archive
archive:
  type: more # less more

# Creative Commons 4.0 International License.
# https://creativecommons.org/licenses/
# Available values of license: by | by-nc | by-nc-nd | by-nc-sa | by-nd | by-sa | zero
# You can set a language value if you prefer a translated version of CC license.
# CC licenses are available in 39 languages, where you can find the specific and correct abbreviation you need.
# Valid values of language: deed.zh, deed.en, deed.ja, etc.
creative_commons:
  license: by-nc-sa
  language: deed.zh
  post: true
  clipboard: true

# Reward (Donate)
# If enable true, reward would be displayed in every posts and pages by default.
# You can show or hide reward in a specific page throuth `reward: true | false` in Front Matter.
reward:
  enable: false
  comment: reward.comment
  # url:
  methods:

# Article table of contents
toc:
  enable: true
  list_number: true
  max_depth: 3
  min_depth: 1

# img loading="lazy"
lazyload:
  enable: true

# Page Visit Statistics
webAnalytics:  
  enable: false 
  baidu:   # Baidu key
  google:  # Tracking ID for Google statistics
  tencent: # Tencent statistics
    sid:
    cid:

# comment
comment:
  bComments:
    enable: false
    env: # 腾讯云环境id
  twikoo:
    enable: false
    envId:   # 腾讯云环境id
  # region: # 环境地域，默认为 ap-shanghai，如果您的环境地域不是上海，需传此参数
  # option: # 用于区分不同文章的自定义 js 路径，如果您的文章路径不是 location.pathname，需传此参数

# Theme mode 
theme: 
  switch: true 
  default: style-light # style-light style-dark

# Service Worker  开始 PWA 只需要设置 sw 为 true 即可，本主题已添加 Server Worker 相关操作 。
sw: false

# Post wordcount
# https://github.com/willin/hexo-wordcount
wordcount:
  enable: true
  count: true
  time: true

# That is it only render those page which has `katex: true` in Front-matter.
# math fomula
# https://katex.org/
katex:
  copy_tex: true
  global: false
  # Options are for katex rendering options: https://katex.org/docs/options.html
  # In page katex options are also possible and will be merged
  options: {}

# Blog search
search:
  enable: true
  type: local #local engine
  # href: 'https://www.google.com/search?q=site:'
  # href: "https://www.baidu.com/s?wd=site:"
  # href: "https://www.bing.com/search?q=site:"
  domain: 
  preload: true #是否预加载搜索。
  # trigger: true #默认回车或点击时触发搜索，设置为 auto 时 input 触发搜索。

# Think of swup as being pjax on steroids. The concepts are similar to those used in barba.js or other transition libraries.
# https://swup.js.org/
# Whether swup is enabled
swup: false

# Datetime formatting
datetime_foramt:
  post_card:
    date: YY/MM/DD
    time: HH:mm
  post_info:
    date: MM/DD
    time: HH:mm
  archive:
    date: MM/DD
    time: HH:mm